apiVersion: apps/v1
kind: Deployment
metadata:
  name: robot-produce
  namespace: team6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: robot-produce
  template:
    metadata:
      labels:
        app: robot-produce
    spec:
      containers:
        - name: robot
          image: 192.168.1.129:5000/team6/robot-service:latest
          imagePullPolicy: Always
          env:
            - name: ROBOT_NAME
              value: "produce"
            - name: INVENTORY_ADDR
              value: "172.16.2.99:30081"
            - name: ZMQ_SUB_ADDR
              value: "tcp://172.16.2.99:30557"
