frr version 10.5.1
frr defaults traditional
hostname r1
service integrated-vtysh-config
log stdout

interface eth1
 ip address 10.0.41.2/24
 ip ospf cost 10

interface eth2
 ip address 10.0.12.1/24
 ip ospf cost 100

interface eth3
 ip address 10.0.13.1/24
 ip ospf cost 25

router ospf
 network 10.0.41.0/24 area 0
 network 10.0.12.0/24 area 0
 network 10.0.13.0/24 area 0
