frr version 10.5.1
frr defaults traditional
hostname r4
service integrated-vtysh-config
log stdout

interface eth1
 ip address 172.16.1.1/24

interface eth2
 ip address 10.0.41.1/24
 ip ospf cost 10

router ospf
 network 172.16.1.0/24 area 0
 network 10.0.41.0/24 area 0
